env:
  TARGET_ENV: "branch"

components:
  - name: mcs-help
    replicas: 1
    ports:
      - port: 3000
    ingress:
      rules:
        - hostname: branch-name.ingress.infra.devmail.ru
          paths:
          - path: /
