version: "3.5"

services:
  docs-private:
    image: stage-registry.infra.devmail.ru/infra/front/new-help
    volumes:
      - ./docs:/home/node/app/docs
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
