env:
  TARGET_ENV: "branch"
  AI_SEARCH_TOKEN: '{{ requiredEnv "TEST_AI_SEARCH_TOKEN" }}'
  SATORI_API_URL: "https://satori.devint.vkc.devmail.ru"

components:
  - name: mcs-help
    replicas: 1
    ports:
      - port: 3000
        headlessOnly: true
    probes:
      liveness:
        path: /docs/api/healthz
        port: 3000
        initialDelaySeconds: 20
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readiness:
        path: /docs/api/healthz
        port: 3000
        initialDelaySeconds: 20
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    ingress:
      rules:
        - hostname: {{ .Release.Store.ingressHostname }}
          paths:
          - path: /
      tls:
        - secretName: front-wildcard-tls-secret
